apiVersion: v1
kind: Pod
metadata:
  name: mlops-pod
spec:
  containers:
  - name: mlops_assignment-fastapi-1
    image: python:3.10.3-slim-bullseye
    command: ["uvicorn", "mri_tool:mlops_assignment", "--host", "0.0.0.0", "--port", "8888"]
    ports:
    - containerPort: 8888
    volumeMounts:
    - name: log-volume
      mountPath: /code/log
  volumes:
  - name: log-volume
    hostPath:
      path: logs
